import React, { useState, useMemo } from "react"
import ReactQuill from "react-quill"
import "react-quill/dist/quill.snow.css"
import { useEnrollments } from "../hooks/useEnrollments"
import { useAllNotes } from "../hooks/useAllNotes"
import { useDocuments } from "../hooks/useDocuments"
import { EnrollmentDetails } from "./EnrollmentDetails"
import { ProgrammeMonthlyStats } from "./ProgrammeMonthlyStats"
import { EcoleMonthlyStats } from "./EcoleMonthlyStats"
import { VilleMonthlyStats } from "./VilleMonthlyStats"
import { DegreMonthlyStats } from "./DegreMonthlyStats"
import { GenreMonthlyStats } from "./GenreMonthlyStats"
import { InterventionsSuiviMonthlyStats } from "./InterventionsSuiviMonthlyStats"
import { InterventionsSansSuiviMonthlyStats } from "./InterventionsSansSuiviMonthlyStats"
import { InterventionsParProgrammeStats } from "./InterventionsParProgrammeStats"
import { AgeGenreStats } from "./AgeGenreStats"
import { DemeurAvecMonthlyStats } from "./DemeurAvecMonthlyStats"
import { OrigineMonthlyStats } from "./OrigineMonthlyStats"
import { EnrollmentForm } from "./EnrollmentForm"
import { ProgrammeDistributionChart } from "./ProgrammeDistributionChart"

import { lumi } from "../lib/lumi"
import toast from "react-hot-toast"
import { useThemeContext } from "../contexts/ThemeContext"
import { formatDate, formatDateTime } from "../utils/dateFormat"

// ... keep existing code
